### ISSUE TITLE
Higher fire OS

### ISSUE THREAD

**Issue by Awaken-01** [daboynb/Root_firestick#2]
I have a firestick with fire OS 7.6.6.8 or something like that, which is higher than required. What should I do? I can't find anything on the internet either...

**Comment by daboynb** [comment]
which model of firestick do you have?

**Comment by Awaken-01** [comment]
> which model of firestick do you have?

Fire Stick 3rd gen (sheldonp)

**Comment by Awaken-01** [comment]
What if try your method despite the fire os being higher? Will I brick it?

**Comment by daboynb** [comment]
you can brick it, sadly for that version there aren't methods available right now
